swagger.yaml

A swagger spec to filter datasets
review the endpoints provided by the spec
anyone in team a and b

swagger spec for the filter api

---

api/api.go
api/api_test.go
api/datastore.go
api/filters.go
mocks/datastore.go
models/models.go
postgres/postgres.go
postgres/postgres_test.go
scripts/InitDatabase.sql

* New endpoints to include getting list of dimension urls, list of
dimension option urls and check if either dimension or option exists
* Extend tests to cover new endpoints
* Handle new response messages when status response is not found
* Update field name `value` to `option` in postgres table and hence
update script
Run tests, make sure changes meets coding standards. Check endpoints match swagger spec; this will include error responses as well as the response models.
Team B

Include new GET request endpoints

---

api/api.go
api/api_test.go
api/datastore.go
api/filters.go
mocks/datastore.go
models/models.go
postgres/postgres.go
postgres/postgres_test.go
scripts/InitDatabase.sql

* New routes for updating dimensions against a filter job and updating
the dimension options against a filter job.
* Extend tests
* Update postgres setup script (add constraint against dimensions table)
Run tests, make sure changes meets coding standards. Check endpoints match swagger spec; this will include error responses as well as the response models.
Team B

Include two new endpoints to post new dimensions or dimension options

---

main.go

Common http handlers for healthcheck, requestID, reverse proxy and
timeout handling.
Check logged http response when making a request to the filter API.
Team A or B

Add go-ns server package to use common HTTP handlers

---

swagger.yaml

Endpoint now allows to update downloads and events object if user is
authenticated.
Check swagger spec caters for user needs (internally as well as externally)
Team B

Update swagger spec PUT endpoint on `/filter/<filter_id>`

---

postgres/postgres.go

Ensure transactions are either committed or rolled back. 
Creating a tranaction without rollback/ commit was leaking connections.
Test
Anyone + @Matt-Guest

Ensure transactions are either committed or rolled back. 

---

cmd/dp-filter-api/main.go
mongo/filterstore.go

Filter dimensions added to mongo
review code
anyone

POST, PUT and DELETE for dimensions

---

mongo/filterstore.go

Added GET, POST and DELETE for dimension options
review the code and test out code using the swagger spec
anyone

GET, POST and DELETE for dimensions options

---

mongo/filterstore.go

Stop duplicate dimension options being added to a filter job
Review the code and run the acceptance tests. See https://github.com/ONSdigital/dp-api-tests/pull/7
Anyone

Stop duplicate dimension options being added to a filter job

---

mongo/filterstore.go

Closed mongo connections
Make errors more idiomatic
Stopped exporting fields which aren't used externally
Ensure code works
Anyone

Add defer session.Close() to mongo functions and address lint comments

---

README.md

Update end year for copyright
Typos
Anyone

Update end year for copyright

---

Makefile
README.md
api/api_test.go
api/filters.go

hide authenticated endpoints
review the code, run unit tests and acceptance tests
anyone

PUT on /filter-outputs/{id} returns 404 when no auth key is provided

---

api/filters.go

so let's ensure it's a string, rather than a struct that doesn't JSONify

when HUMAN_LOG is off, `err` fails to json.Marshall, so is blank

---

dp-filter-api.nomad

Set correct vault policies for publishing / web

Set correct vault policies for publishing / web

---

dp-filter-api.nomad

remove nomad service name suffix

remove nomad service name suffix

---

api/filters.go

Populate the last updated field for new filter outputs
Ensure nothing breaks
Anyone

Add current time to filter outputs on creation

---

config/config_test.go

Fix failing test

---

swagger.yaml

Update summaries and descriptions to standardize for dev site
Removed the word blueprint because its meaningless to users
Check swagger spec is still valid
Check updates make things clearer
Anyone

Update summaries and descriptions to standardize for dev site

---

api/filter_outputs.go
api/filter_outputs_test.go

Hide public links unless a download service token is given
Review / test
Anyone

Hide public links unless a download service token is given

---

swagger.yaml

Update PUT /filters/<id> endpoint description to clarify how to submit a filter (this was previously in the top level API description but has been removed.
Ensure changes are accurate and improve clarity
Anyone

Update description in spec for how to submit filters

---

api/filters.go

The log message didn't match the style/flow of other messages when debugging
See if this makes more sense
Anyone

Update log message to be more concise

---

api/filter_dimensions.go
api/filter_outputs.go
api/filters.go
vendor/github.com/ONSdigital/go-ns/request/request.go
vendor/github.com/ONSdigital/go-ns/request/util.go
vendor/vendor.json

Drain HTTP request body in handlers that use it
Review changes / test
Anyone

Drain HTTP request body in handlers that use it

---

api/filter_dimension_options_test.go
models/models.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/data.go
vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/vendor.json

Removed custom definitions for dimensions from this API where they should be provided by the client
Check tests pass and expected functionality is maintained
anyone

Update use of dataset API client to simplify dimensions

---

api/filter_dimension_options.go
api/filter_dimension_options_test.go
api/filter_dimensions.go
api/filter_dimensions_test.go
mocks/datastore.go
swagger.yaml
vendor/github.com/gorilla/mux/AUTHORS
vendor/github.com/gorilla/mux/ISSUE_TEMPLATE.md
vendor/github.com/gorilla/mux/LICENSE
vendor/github.com/gorilla/mux/README.md
vendor/github.com/gorilla/mux/doc.go
vendor/github.com/gorilla/mux/go.mod
vendor/github.com/gorilla/mux/middleware.go
vendor/github.com/gorilla/mux/mux.go
vendor/github.com/gorilla/mux/regexp.go
vendor/github.com/gorilla/mux/route.go
vendor/github.com/gorilla/mux/test_helpers.go
vendor/vendor.json

- Ensure the POST endpoints return a request body to be consistent with other APIs
- Ensure DELETE endpoints return http status 204 as no content is returned
- Update spec to reference ID, rather than filter_id (since it is already in the filter namespace)
- Update gorilla package to return http status 405 when method is not supported
Run the unit tests
Run the filter api acceptance tests on branch `feature/filter-api-issues`
Review Code
Anyone

Filter API issues

---

vendor/github.com/ONSdigital/dp-filter/observation/reader.go
vendor/github.com/ONSdigital/dp-filter/observation/store.go
vendor/vendor.json

- update query for efficiency
- includes changes to return observation count
check filter queries continue to work
anyone

Update vendor of observation filter package for efficiency

---

swagger.yaml

Update swagger spec to include skipped flag on download files
sanity check
anyone

Update swagger spec to include skipped flag on download files

---

api/filter_outputs.go
mongo/filterstore.go

Update logic in mongo updates to include changes when the skipped flag is set
Update log message to remove duplication/improve clarity
Test when sending a 'skipped' flag on a download item that the record in mongo is updated
anyone

Update mongo store functions to include skipped flag

---

api/filter_outputs.go

Only generate href when size has been provided, so other services have confidence that an href will resolve to content
test href only exists in responses when appropriate
anyone

Only generate href when size has been provided

---

dp-filter-api.nomad

What
Using docker reduces the likelihood of timeout on deploy
How to review
check for typos
check repo names are consistent
check web/publishing both updated
Who can review
anyone

Update nomad plan to use docker instead of exec driver

---

vendor/github.com/ONSdigital/dp-filter/observation/store.go
vendor/vendor.json

Update dp-filter vendor with changes for safer variable names
check filter preview still works
anyone

Update dp-filter vendor for safer variable names

---

vendor/github.com/ONSdigital/dp-filter/observation/store.go

Changed something in a vendor'd package to make sure it's actually the fix (we don't have any logs - fingers crossed). Will do it properly if it actually works.
Sanity check.
Anyone.

horrible vendor hack

---

vendor/github.com/ONSdigital/dp-filter/observation/store.go

Reverting a stab-in-the-dark that didn't pan-out.
Don't. Just press approve. This is a roll-back to previously reviewed and working code.
Anyone.

revert temporary change

---

cmd/dp-filter-api/main.go

Pass new abstracted graph into healthcheck to monitor graph connection
check healthcheck monitors graph
anyone

Reimplement graph healthcheck

---

preview/preview.go

Add logging to preview to aid debugging between db or data issue
sanity check, tests pass, logging comes out on preview requests
anyone

Add logging to preview to aid debugging between db or data issue

---

preview/preview_test.go
vendor/github.com/ONSdigital/dp-graph/mock/observation.go
vendor/github.com/ONSdigital/dp-graph/neo4j/neo4j.go
vendor/github.com/ONSdigital/dp-graph/neo4j/observation.go
vendor/vendor.json

Fix compiling issue with dependency and mismatched mock func call
check `make debug` and `make test` pass
anyone

Fix compiling issue with dependency and mismatched mock func call

---

vendor/github.com/ONSdigital/dp-dimension-importer/LICENSE.md
vendor/github.com/ONSdigital/dp-dimension-importer/model/models.go
vendor/github.com/ONSdigital/dp-graph/config/config.go
vendor/github.com/ONSdigital/dp-graph/graph/driver/driver.go
vendor/github.com/ONSdigital/dp-graph/graph/driver/errors.go
vendor/github.com/ONSdigital/dp-graph/graph/graph.go
vendor/github.com/ONSdigital/dp-graph/mock/dimension.go
vendor/github.com/ONSdigital/dp-graph/mock/doc.go
vendor/github.com/ONSdigital/dp-graph/mock/hierarchy.go
vendor/github.com/ONSdigital/dp-graph/mock/instance.go
vendor/github.com/ONSdigital/dp-graph/mock/observation.go
vendor/github.com/ONSdigital/dp-graph/neo4j/codelists.go
vendor/github.com/ONSdigital/dp-graph/neo4j/dimension.go
vendor/github.com/ONSdigital/dp-graph/neo4j/driver/driver.go
vendor/github.com/ONSdigital/dp-graph/neo4j/driver/healthcheck.go
vendor/github.com/ONSdigital/dp-graph/neo4j/driver/row_reader.go
vendor/github.com/ONSdigital/dp-graph/neo4j/hierarchy_reader.go
vendor/github.com/ONSdigital/dp-graph/neo4j/hierarchy_writer.go
vendor/github.com/ONSdigital/dp-graph/neo4j/instance.go
vendor/github.com/ONSdigital/dp-graph/neo4j/mapper/common.go
vendor/github.com/ONSdigital/dp-graph/neo4j/mapper/datasets.go
vendor/github.com/ONSdigital/dp-graph/neo4j/mapper/editions.go
vendor/github.com/ONSdigital/dp-graph/neo4j/mapper/hierarchies.go
vendor/github.com/ONSdigital/dp-graph/neo4j/neo4j.go
vendor/github.com/ONSdigital/dp-graph/neo4j/observation.go
vendor/github.com/ONSdigital/dp-graph/neo4j/query/query.go
vendor/github.com/ONSdigital/dp-hierarchy-api/LICENSE.md
vendor/github.com/ONSdigital/dp-hierarchy-api/models/response.go
vendor/github.com/ONSdigital/dp-hierarchy-api/models/storer.go
vendor/vendor.json

Update vendor for dp-graph to include documentation and make sure everythings up to date with latest dp-graph changes (also ensuring apps which were migrated first are compatible with later changes)
check everything works as usual
anyone

Update vendor for dp-graph to include documentation

---

vendor/github.com/ONSdigital/go-ns/clients/dataset/dataset.go
vendor/github.com/ONSdigital/go-ns/common/collection.go
vendor/vendor.json

updated datasetAPI client

---

api/api.go
vendor/github.com/ONSdigital/go-ns/common/collection.go
vendor/github.com/ONSdigital/go-ns/handlers/collectionID/handler.go
vendor/vendor.json

Added collection ID handler to middleware.
Sanity check.
Anyone.

added collection id handler

---

api/filters.go

reduce logging of dimensions, too

---

api/filters.go

logging for performance testing.

added submitted log event to aid with performance testing

---

api/api.go

To allow upstream services to pass healthcheck - transitional code and this should be removed at a later date
- Check both `/health` and `/healthcheck` endpoints return health state object
- Make sure unit tests pass
Anyone

Add old health check endpoint /healthcheck

---

swagger.yaml

Documentation for creating a working patch endpoint for internal services
Check specification makes sense
- data structures
- descriptions
- headers - specifically use of If-Match and ETag
Anyone

Update swagger spec - PATCH dimension endpoint

---

Makefile
ci/audit.yml
ci/scripts/audit.sh

Implement dependency auditing with Nancy
- Check changes align with other implementations for dependency auditing within our services
- Ensure correct permissions are set for the `audit.sh` file (chmod 755)
Anyone

dependency auditing implementation

---

api/filters.go
filterOutputQueue/filterOutputQueue.go
filterOutputQueue/filterOutputQueue_test.go

See title
Exporter services need this information to build human friendly filenames to store in s3
Check code changes make sense and unit tests pass
Anyone.

Add dataset Id, edition and version into filter output topic event

---

ci/build.yml
ci/unit.yml

See title
- Check ci config files contain specific version of go
Anyone

Update go version to a specific one in ci config files

---

service/service.go

- Added some code comments to document the case of a missing dependency (MongoDB) that does not cause the service to exit.
- Service initialisation: do not return on error
- Register checkers: create a critical handler
Make sure the comments are clear.
Anyone

Documented uninitialised mongoDB dependency case

---

service/service.go

Make the code clearer to understand.

Refactor registerCheckers to make clearer.

---

config/config_test.go
go.mod
go.sum
mongo/filterstore.go

- Update mongo-db library to 1.5.0
- Include database and collections in the healthcheck
Check that the tests pass, and that how the collection and database are built to be passed into the healthcheck makes sense for this application
Helene worked on the changes, so anyone except myself

Update mongodb to v1.5.0 and include collections in healthcheck

---

mongo/filterstore.go

- Build the collections name for a database into an array so all the collections can be passed into the healthcheck client and checked
Test that when either of the collections isn't in the mongodb database the healthcheck fails
Anyone

Update the map so the collections are passed in as an array

---

api/filter_dimension_options_test.go
api/filters.go
go.mod
go.sum
models/models.go

encode ID query params
-
anyone

encode id query parameters when requesting options to dataset api

---

api/filter_outputs.go
api/filters.go
models/models.go
swagger.yaml

FilterOutputResponse and BluePrint do not contain a overall id field. Copied over filter_id to id field.
check the code changes.
Anyone with golang understanding.

introduce id field for filterOutput and filter blueprint responses.

---

LICENSE.md
README.md

update the license and year.
Verify the changes
Anyone

update license and readme years.

---

mongo/filterstore.go

Added lines after mgo.Dial() as per other apps:
session.EnsureSafe(&mgo.Safe{WMode: "majority"})
session.SetMode(mgo.Strong, true)
Inspect code.
With mongodb and other services (if needs be) running, run with: make debug
and check that no RACE conditions seen.
Anyone.

Fix RACE seen when running app with - make debug

---

utils/utils.go

Fix adding existing options to filters api
- Handle updating empty options to filters.
Ensure adding existing options to filters is working.
anyone

fix adding existing option to filter issue

---

models/models.go

- omit empty options in bson
Ensure new filters are created successfully
anyone

Omit empty options while creating or updating a filter

---

config/config.go
config/config_test.go
service/service.go

Added FilterFlexapiURL to config instead of being hardcoded
Check change makes sense
Anyone

add filterflex api url to config

---

swagger.yaml

Update the changes to the swagger spec by adding the filter_by_parent attribute
View additions and check okay 
team b

swagger: add filter_by_parent to dimension

---

api/api.go
api/filter_outputs_test.go

Commented out auth check
Describe the steps required to test the changes.
Anyone

test to see if the error is surely with auth

---

api/api.go
api/filter_outputs_test.go

Reintroduced reverted code
Test are green
Anyone

Reintroduced auth for filter_outputs

---

api/api.go
api/filter_outputs_test.go

Removed authorisation for **/filter-outputs/{filter_output_id}** endpoint
All test pass
Anyone

removed auth 

---

go.mod
go.sum

##What
upgraded github.com/gorilla/schema v1.1.0 => v1.4.1
##How to review
Check if the build checks are passing as expected.
##Who can review
Anyone

dependancy updated

---

middleware/assert.go

Added logging for debugging within sandbox
Check changes are ok
Anyone

added logs for X-Forwarded-Host and path prefix

---

middleware/assert.go

Added test host into header for debugging
Check changes are ok
Anyone

added test host header

---

middleware/assert.go

Removed logging for headers
Check changes are ok
All logging has been removed
Anyone

removed logging for headers

---

api/api.go
api/filter_dimension_options_test.go
api/filter_dimensions_test.go
api/filter_outputs.go
api/filter_outputs_test.go
api/filters_test.go
config/config.go
config/config_test.go
service/service.go

- added internal download service url to config file
- updated unit tests
- check if the Download links are rewritten properly when calling 'filter-outputs'
- check if the build checks are passed
@anyone

added internal download service URL variable

---

go.mod
go.sum

fixed crypto dependency audit failure by updating the version
check if the audit build check is passed
anyone

audit failure fix
