ONSdigital/dp-filter-api

swagger.yaml

The /filter job creation was defining dimensions using a different structure than the one being returned. This change consolidates that into a single format
Sanity check the changes don't cause problems for any other areas and that the right approach has been taken 
@Matt-Guest or @ian-kent 
(or anyone else who fancies it)

Update swagger spec to use consistent structure for dimensions

---

README.md
api/api.go
api/api_test.go
api/datastore.go
api/filters.go
config/config.go
config/config_test.go
main.go
mocks/datastore.go
models/models.go
postgres/postgres.go
swagger.yaml

Extend PUT request to handle authentication header; this allows backend services to update the filter job when the state is set to `submitted`.
Also includes: 
* Additional logic on endpoints to update filter job to prevent users updating a job if it is already completed
* Update swagger spec
* Correctly returned error messages to match swagger spec
Run tests, make sure changes meets coding standards. Check endpoints match swagger spec; this will include error responses as well as the response models.
Team B

 Extend PUT request to handle authentication header

---

README.md
config/config.go
config/config_test.go
main.go
postgres/postgres.go
postgres/postgres_test.go
scripts/InitDatabase.sql
vendor/github.com/ONSdigital/go-ns/handlers/requestID/handler.go
vendor/github.com/ONSdigital/go-ns/handlers/timeout/handler.go
vendor/github.com/ONSdigital/go-ns/server/server.go
vendor/github.com/justinas/alice/LICENSE
vendor/github.com/justinas/alice/README.md
vendor/github.com/justinas/alice/chain.go
vendor/vendor.json

Update PUT endpoint `/filters/<filter_job_id>` to allow Downloads table to be updated by authenticated users. 
If authentication fails return error status 401 (unauthenticated), if auth token is not set in header of request and the filter job has been submitted then error status returned is 403 (forbidden) otherwise returns a 400 (bad request) when a user trys to update downloads table.
Also includes:
* Fix idle connections, these were previously not being closed on calling external Query method.
Run tests, make sure changes meets coding standards. Check endpoints match swagger spec; this will include error responses as well as the response models.
Team B

Authenticated users allowed to update Downloads table vi 

---

api/api_test.go
api/datastore.go
api/filters.go
mocks/datastore.go
models/models.go
postgres/postgres.go
postgres/postgres_test.go
swagger.yaml

Includes the following: 
* General tidy up of response messages when request fails.
* Update response body for GET request on `/filters/<filter_job_id>/dimensions/<name>/options` to return an array of option objects containing the dimension option url and the option value.
* Update response body for POST request on `/filters` to return `dimension_url` and NOT return dimension object.
Check code matches swagger specs. Changes adhere to coding standards. Check tests still pass by running `make test`. 
Team A or Team B

Fix inconsistent error responses and swagger spec

---

api/filters.go

Change filter api auth header to use hyphen instead of underscore.

Change filter api auth header to use hyphen instead of underscore.

---

api/api_test.go
api/filters.go
dataset/api.go
mocks/datasetapi.go
models/instance.go

Handle different error status's in responses from dataset API. Also prevent users from filtering unpublished datasets.
Check logic and tests still pass
Team B

Handle different error status's in responses from dataset API

---

swagger.yaml

Filter job does not exist anymore instead there is a filter blueprint
which a user can update as many times as they like even after they
submit the resource. Once submitted a filter output resource is created
and cannot be updated by external users. The filter output is then
updated by backend process once the downloads are available. In the
meantime the filter blueprint can be used to create another filter
output.
Check specification makes sense, all error status's are accounted for.
Team A or B

Update swagger specs to to separate filters from job

---

mocks/datastore.go
models/models.go
mongo/filterstore.go

Ensure we're not adding the same dimension multiple times by replacing it in the list it lives in and setting that list rather than adding to it.
Ensure API requests look sane and tests pass
Using filter journey on the website, try adding all time values and returning to the filter hub page - you should only see 1 time dimension with the number of options filled in.
@mattrout92 & @nshumoogum or @Matt-Guest

Replace dimension in list rather than adding to list

---

mongo/filterstore.go

Updated a mongo query so that it only writes selected fields rather than overwriting entire document
Ensure when updating the filter (particularly from 'created' to 'submitted') that dimensions dont get removed, download links get added, and state updates to completed.
Anyone

Fix update filter mongo query to only set limited fields

---

swagger.yaml

As a basic preview version the results are returned as two dimensional
array, the headers are seperated, columns and rows sizes are
shown.
read the swagger spec
anyone

Updated swagger sepc for filter preview

---

cmd/dp-filter-api/main.go

The first neo4j connection in the pool is lost, as the connection is not used or closed.
Review the code
anyone

The first neo4j connection is lost in the pool

---

api/filters.go
models/models.go
mongo/filterstore.go
mongo/filterstore_test.go
swagger.yaml

The filter-api already supported this but there was a bug
which needed to be addressed before events could be added
to a filter output.
Added more information in the swagger spec about completed and
failed jobs.
review code and swagger spec
anyone

Allow events to be passed to the filter api

---

api/api_test.go
api/dataset.go
api/filters.go
mocks/datasetapi.go
mocks/datastore.go
models/models.go
models/models_test.go
models/version.go
swagger.yaml

Use dataset_id, edition and version to create a filter job. This change is needed as the filter api can no longer call the instance endpoints on the dataset api
review the code, run the unit tests. 
Anyone

Move away from using the instance id and to fetch datasets

---

api/api.go
api/api_test.go
api/dataset.go
api/filters.go
api/filters_test.go
cmd/dp-filter-api/main.go
config/config.go
mocks/datastore.go
models/models.go
models/models_test.go
mongo/filterstore.go
mongo/filterstore_test.go
swagger.yaml

Update filterOutput resource with private and public links (incl. specs)
Also includes:
* updating GetFilterOutputs endpoint to hide private links if
user is not authorised
* updating PutFilterOutputs endpoint to prevent updates to downloads
object when the public link already exists and the version is
published
Unit tests updated and extended for both validation and api tests
Check changes made make logical sense and unit tests pass as well as the filterAPI acceptance tests on branch `feature/filter-private-public-links`, e2e tests will fail as this feature needs several other services to be merged into cmd-develop as well as PR's on the `dp-api-tests` repo.
Team B

Update downloads object to contain public and private links

---

Makefile
config/config.go
config/config_test.go

Default to publishing 'mode' via config instead of makefile
Allowing it to be overridden

Default to publishing 'mode' via config instead of makefile

---

README.md
api/api.go
api/api_test.go
api/filters.go
cmd/dp-filter-api/main.go
config/config.go
config/config_test.go

Private links were previously being returned only for authenticated requests. This fails on web now that it does not have authentication. It has been updated to return private links given a valid download service token - the same as the dataset-api
Review / test with https://github.com/ONSdigital/dp-api-tests/pull/69
Anyone

Return private download links when valid download service token is given

---

api/filter_outputs.go

Ensure filter output state is set as its current value. This was previously defaulting to `created` in the mongo package. Now that its been refactored out of there it was not being defaulted, and hence it was an empty string. There is a conditional further on in the code that checks for a created state. This was failing due to the empty value.
Review changes
Anyone

Ensure filter output state is set as its current value

---

api/filter_outputs.go
api/filter_outputs_download_test.go
api/filter_outputs_test.go
models/models.go

Add 'skipped' flag to download items
Allow filters to be marked 'complete' when an output has been marked as skipped
goes with:
https://github.com/ONSdigital/dp-dataset-exporter/pull/58
https://github.com/ONSdigital/dp-dataset-exporter-xlsx/pull/76
test setting skipped flags marks outputs as complete
anyone

Add 'skipped' to download items and complete filter output if skipped

---

api/filter_outputs.go
api/filter_outputs_download_test.go

-refactored the logic to hopefully be clearer
- ensured that download items which are marked as skipped return a document with a skipped field rather than empty doc
check tests pass and logic makes sense - if PUT body supplied a 'skipped = true' then the download item should return a download item with a skipped flag and no other fields populated. 
anyone

Update filter output download logic to correctly propagate skipped

---

cmd/dp-filter-api/main.go
initialise/initialise.go

Prevent application falling over on start up due to external services not being available. Also remove call to gracefully shutdown when the service loses connections to other internal or external services; it should only shutdown due to the platform running application informs the service to close using system a call to interrupt or terminate the application.
- Check service does not shutdown on startup if an external service (e.g. kafka) is not available (running)
- Check service does not call graceful shutdown if an external service (again easy to use kafka) becomes unavailable
- Check system call for termination and interrupt force a graceful shutdown
- Check unit tests pass
Anyone

Prevent app closure on startup

---

cmd/dp-filter-api/main.go

Prevent service shutting down when the service receives an api or kafka error after it previously successfully started up.
Switch statement that allows graceful shutdown to run blocks until an os signal (interrupt or terminate) is received.
Check app does not shutdown early, setup:
1) Start app up (make sure all external service dependencies are running)
2) Once app has been confirmed to be healthy, terminate kafka
3) Send a request to build a filter blueprint, the app should not exit as it is unable to write messages to kafka topic
4) Instead an error should be logged
Check unit tests pass
Anyone

Fix call to graceful shutdown when api or kafka error is received

---

service/service.go

Removed code related to old /healthcheck endpoint, as per this ticket - https://trello.com/c/ECS9esvf/4743-filter-api-remove-transitional-health-check-code-1d
Run service locally and confirm that /healthcheck endpoint returns a 404 error
Anyone

Removed code related to old /healthcheck endpoint

---

go.mod
go.sum
service/service_test.go

- Upgraded `dp-api-clients-go` version to fix dataset get options by list of IDs.
- Increased shutdown timeout and sleep for testing to minimize the probability of a race condition with context switching.
- Make sure that dp-api-clients-go was upgraded to version 1.32.1
- Make sure unit tests pass
Anyone

Update dp-api-clients-go dependency to fix id query parameter

---

api/api.go
api/filter_dimension_options_test.go
api/filter_dimensions.go
api/filters.go
api/mocks/datasetapi.go
config/config.go
go.mod
go.sum
mocks/datasetapi.go

(depends on https://github.com/ONSdigital/dp-api-clients-go/pull/84)
- Use `GetOptionsBatchProcess` instead of `GetOptions` to validate options by ID with dataset API.
- Adapted unit tests accordingly
- Make sure code changes make sense
- Make sure unit tests pass
- (optinal) I already tested it manually:
- export a small batch size: `export MAX_DATASET_OPTIONS=2`
- `make debug`
- With postman, apply a patch with 5 IDs: {id1, id2, id3, id4, id5}
- Check logs and validate that the dataset api is called 3 times: {id1, id2}, {id3, id4}, {id5}
Anyone

use dataset GetOptionsBatchProcess for options validation by ID

---

api/filters.go

Bug fix: for dimensions with empty lists of options, we used did a call to validate with offset=0 and limit=0. This is wrong and unnecessary, so we handle the case by returning early if no options are provided (nothing to validate)
Make sure code changes make sense
Anyone

If a dimension does not provide options, don't try to check them

---

Makefile
go.mod
go.sum

- Updated Makefile with the correct audit command
- Fixed vulnerability by upgrading gorilla/websocket from version 1.4.0 to 1.4.2
- Make sure the audit CI step is successful
- Make sure nothing else changed
Anyone

fixed audit command in Makefile, and upgraded dependency to fix vulnerability

---

go.mod
go.sum

Upgrade dp-api-clients-go version to make sure the list of IDs is correctly escaped.
Make sure that the version of `dp-api-clients-go` is updated to 1.32.6
Anyone

Upgrade dp-api-clients-go version to make sure the list of IDs is correctly escaped.

---

api/filter_outputs.go
api/filters.go

Fixed a faulty assignment which would leave the links object empty for a filter blueprint.
Test CMD filter/download still works. Check links for 'Adjust filter options' and 'Filter options' breadcrumb now work correctly.
Anyone

Fix missing filter blueprint links

---

api/api.go
api/filters_test.go

Added the assert-filter-type middleware to GET /filters/id/dimensions
Check change makes sense, tests pass
Anyone

wrap get dimensions endpoint with middleware, add unit tests

---

swagger.yaml

Attempted to correct the filter-api swagger spec for POST to /filters
1. Added "population_type" field (type string) which is an optional field understood by upstream service dp-cantabular-filter-flex-api
2. Added missing "is_based_on" field do Dataset
3. Added the model for IsBasedOn - copied directly from dp-cantabular-filter-flex
Things to consider:
1. population_type field is using the OpenAPI `type` keyword to set the data type, but dp-cantabular-filter-flex service uses the `format` keyword for the same thing - not sure if it matters that they're different (official spec doesn't seem to clarify, but normally base types use the `type` keyword)
2. Adding the is_based_on field to the model for Dataset will add this as an optional field for _every endpoint which uses this definition_. …

updated swagger spec to match target contract

---

api/api.go
api/filter_dimensions.go
api/filter_dimensions_test.go
models/models.go
swagger.yaml

Adds `putFilterBlueprintDimensionHandler` to handle `PUT` requests to `/filters/{filter_blueprint_id}/dimensions/{name}`.
If the given filter is flexible then the request is forwarded to the `dp-cantabular-filter-flex-api` if not an error is returned.
Context:
[https://trello.com/c/vUgHxQLq/5623-add-put-filters-id-dimensons-name-endpoint-to-dp-cantabular-filter-flex-api](https://trello.com/c/vUgHxQLq/5623-add-put-filters-id-dimensons-name-endpoint-to-dp-cantabular-filter-flex-api)
Check the code and API spec makes sense.
Anyone.

Add putFilterBlueprintDimensionHandler handler

---

api/api.go
api/filters_test.go

Forwards requests to `GET /filters/:id/dimension/:dimension` on to the filter flex API, which will handle them as part of [this PR](https://github.com/ONSdigital/dp-cantabular-filter-flex-api/pull/54).
Resolves: 5570 (https://trello.com/c/8xCrDyR1)
Confirm the middleware is used correctly.
Anyone.

Forward flexible GET requests for individual dimensions (#5570)

---

api/api.go
api/filter_outputs_test.go

Proxies get filter outputs requests for flexible datasets onto `dp-cantabular-filter-flex-api`.
Context: [https://trello.com/c/4aCeV3JV/5638-add-proxy-request-to-cantabular-filter-flex-api-in-filter-api-for-get-filter-outputs](https://trello.com/c/4aCeV3JV/5638-add-proxy-request-to-cantabular-filter-flex-api-in-filter-api-for-get-filter-outputs)
Check code and tests.
Anyone

Check filter type on get filter outputs endpoint

---

api/api.go
api/filter_outputs_test.go

This reverts commit d148e53f018bff864ed2aaa65498b7f9cbbc5daa.
Reverts the changes from https://github.com/ONSdigital/dp-filter-api/pull/237.
A fix is being worked on to enable this functionality but for the time being we will revert.
Check the correct changes are reverted.
Anyone.

Revert "Check filter type on get filter outputs endpoint"

---

api/api.go
api/filter_outputs_test.go

Filtering on CMD datasets is currently broken in develop. Once selections
are made by the user and the button is pressed to generate a download
an error is returned.
An error screen is displayed. When looking for the UUID in the URL bar
at the top of the screen in Kibana the below error is returned.
```
"{ "status_code": 500, "response": "failed to get dataset: filter blueprint not found", "error": "failed to get dataset: filter blueprint not found" }"
```
This is due to the `assert.FilterType(...)` being used instead of the
`assert.FilterOutputHandler(...)`
Resolves: [5669](https://trello.com/c/xp5yM8Gp/5669-cmd-filtering-is-broken-on-website-develop)
Review and test locally.
Any developer from Team B

Fix GET /filter-outputs/{id} endpoint 

---

mongo/filterstore.go
mongo/filterstore_test.go

We are not able to search the `CMD` dataset at the moment, as we were searching for an `id` key instead of the `filter_id` key.
Resolves [5669](https://trello.com/c/xp5yM8Gp/5669-cmd-filtering-is-broken-on-website-develop)
Review code.
Any developer

Search filterOutputs using 'filter_id' instead of 'id'

---

go.mod
go.sum
models/models.go
mongo/filterstore.go
mongo/filterstore_test.go

In CMD we search by `filter_id`, but on Cantabular we search by a new
field called `id`.
This addresses the approach of simply changing the MongoDB query.
Resolves: [5690](https://trello.com/c/ZDZgbMyz/5690-copy-getfilteroutput-function-from-dp-filter-api-and-amend-for-cantabular-filter-output-search)
Review the changes and run them locally
Any ONS developer

Search filterOutput collection via "filter_id" or "id"

---

api/api.go
api/filter_dimension_options_test.go
api/filter_flex_handler.go
go.mod
go.sum

Trello ticket #5735
DELETE "/filters/{id}/dimensions/{name}/options"
add to routes to proxy over to cantabular filter flex
api and dummy handler to represent bad state
View the changes.
It was judged that testing was not required as middleware tests are already detailed in testing that requests are appropriately forwarded.
Team B

feat: add delete options proxy
